// Code generated by "stringer -type=Language"; DO NOT EDIT.

package language

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EN-0]
	_ = x[ES-1]
	_ = x[FR-2]
	_ = x[DE-3]
	_ = x[ZH-4]
	_ = x[HI-5]
	_ = x[PT-6]
	_ = x[RU-7]
	_ = x[VI-8]
	_ = x[JA-9]
	_ = x[KO-10]
	_ = x[AR-11]
	_ = x[TL-12]
	_ = x[IT-13]
	_ = x[PL-14]
	_ = x[FA-15]
	_ = x[UR-16]
	_ = x[TH-17]
	_ = x[HE-18]
}

const _Language_name = "ENESFRDEZHHIPTRUVIJAKOARTLITPLFAURTHHE"

var _Language_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38}

func (i Language) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Language_index)-1 {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[idx]:_Language_index[idx+1]]
}
