// Code generated by "stringer -type=Family"; DO NOT EDIT.

package family

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Chrome-0]
}

const _Family_name = "Chrome"

var _Family_index = [...]uint8{0, 6}

func (i Family) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Family_index)-1 {
		return "Family(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Family_name[_Family_index[idx]:_Family_index[idx+1]]
}
