// Code generated by "stringer -type=Platform"; DO NOT EDIT.

package platform

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Windows-0]
	_ = x[MacOS-1]
	_ = x[Linux-2]
	_ = x[ChromeOS-3]
}

const _Platform_name = "WindowsMacOSLinuxChromeOS"

var _Platform_index = [...]uint8{0, 7, 12, 17, 25}

func (i Platform) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Platform_index)-1 {
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Platform_name[_Platform_index[idx]:_Platform_index[idx+1]]
}
