// Code generated by "stringer -type=Module"; DO NOT EDIT.

package modules

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Amazon-0]
	_ = x[Microsoft-1]
	_ = x[Facebook-2]
}

const _Module_name = "AmazonMicrosoftFacebook"

var _Module_index = [...]uint8{0, 6, 15, 23}

func (i Module) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Module_index)-1 {
		return "Module(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Module_name[_Module_index[idx]:_Module_index[idx+1]]
}
